name: "Workflow of satellite 1"

on:
  push:
    branches:
      - main

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    shell: bash
    run: |
      echo "Executing workflow of satellite 1"
